# Generated by Django 6.0.5 on 2026-06-22 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('legajo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alumno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Arancel',
            fields=[
                ('id_arancel', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'arancel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.IntegerField()),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'aula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DisciplinaDeportiva',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('horarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disciplina_deportiva',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('legajo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'docente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'instalacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('carga_horaria', models.IntegerField()),
                ('cantidad_clases', models.IntegerField()),
            ],
            options={
                'db_table': 'materia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PostulacionLaboral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('puesto', models.CharField(max_length=50)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('cv', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_postulacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'postulacion_laboral',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SolicitudInscripcion',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(max_length=100)),
                ('apellido_alumno', models.CharField(max_length=100)),
                ('dni_alumno', models.CharField(max_length=8)),
                ('fecha_nacimiento', models.DateField()),
                ('nivel', models.CharField(max_length=30)),
                ('turno', models.CharField(max_length=30)),
                ('nombre_tutor', models.CharField(max_length=100)),
                ('apellido_tutor', models.CharField(max_length=100)),
                ('dni_tutor', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_alumno', models.CharField(blank=True, max_length=20, null=True)),
                ('email_alumno', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_tutor', models.CharField(blank=True, default='', max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField()),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('parentesco', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'solicitud_inscripcion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=60, unique=True)),
                ('contrasenia', models.CharField(max_length=20)),
                ('correo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo_asistencia', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Tardanza', 'Tardanza')], max_length=10)),
                ('archivo_justificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('legajo_alumno', models.ForeignKey(db_column='legajo_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.alumno')),
            ],
            options={
                'db_table': 'asistencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('comision', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('turno', models.CharField(max_length=30)),
                ('nivel', models.CharField(max_length=30)),
                ('cupo_maximo', models.IntegerField(blank=True, null=True)),
                ('id_aula', models.ForeignKey(blank=True, db_column='id_aula', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.aula')),
            ],
            options={
                'db_table': 'curso',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_curso',
            field=models.ForeignKey(blank=True, db_column='id_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.curso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_disciplina',
            field=models.ForeignKey(blank=True, db_column='id_disciplina', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.disciplinadeportiva'),
        ),
        migrations.CreateModel(
            name='DocenteDisciplina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_disciplina', models.ForeignKey(db_column='id_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.disciplinadeportiva')),
                ('legajo_docente', models.ForeignKey(db_column='legajo_docente', on_delete=django.db.models.deletion.DO_NOTHING, to='core.docente')),
            ],
            options={
                'db_table': 'docente_disciplina',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField()),
                ('estado', models.CharField(max_length=30)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.curso')),
                ('legajo_alumno', models.ForeignKey(db_column='legajo_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.alumno')),
            ],
            options={
                'db_table': 'inscripcion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='disciplinadeportiva',
            name='id_instalacion',
            field=models.ForeignKey(db_column='id_instalacion', on_delete=django.db.models.deletion.DO_NOTHING, to='core.instalacion'),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(db_column='legajo_alumno', on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
                ('docente', models.ForeignKey(db_column='legajo_docente', on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
                ('materia', models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
            ],
        ),
        migrations.CreateModel(
            name='DocenteDictaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.DO_NOTHING, to='core.docente')),
                ('id_materia', models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.DO_NOTHING, to='core.materia')),
            ],
            options={
                'db_table': 'docente_dicta_materia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursoCursaMaterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarios', models.TextField(blank=True, null=True)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.curso')),
                ('id_materia', models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.DO_NOTHING, to='core.materia')),
            ],
            options={
                'db_table': 'curso_cursa_materias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tipo_evaluacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField()),
                ('legajo_alumno', models.ForeignKey(db_column='legajo_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.alumno')),
                ('id_materia', models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.DO_NOTHING, to='core.materia')),
            ],
            options={
                'db_table': 'calificacion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='id_persona',
            field=models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='core.persona'),
        ),
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='core.persona')),
            ],
            options={
                'db_table': 'directivo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_persona',
            field=models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='core.persona'),
        ),
        migrations.CreateModel(
            name='PersonalAdministrativo',
            fields=[
                ('legajo', models.AutoField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='core.persona')),
            ],
            options={
                'db_table': 'personal_administrativo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(max_length=350)),
                ('fecha_publicacion', models.DateField()),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('legajo_personal', models.ForeignKey(db_column='legajo_personal', on_delete=django.db.models.deletion.DO_NOTHING, to='core.personaladministrativo')),
            ],
            options={
                'db_table': 'noticia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentacionAlumno',
            fields=[
                ('id_documentacion', models.AutoField(primary_key=True, serialize=False)),
                ('dni_frente', models.CharField(blank=True, max_length=255, null=True)),
                ('dni_dorso', models.CharField(blank=True, max_length=255, null=True)),
                ('partida_nacimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('certificado_salud', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_envio', models.DateTimeField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('legajo_alumno', models.ForeignKey(db_column='legajo_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.alumno')),
                ('id_administrativo', models.ForeignKey(blank=True, db_column='id_administrativo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.personaladministrativo')),
            ],
            options={
                'db_table': 'documentacion_alumno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Preceptor',
            fields=[
                ('legajo', models.AutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='core.persona')),
            ],
            options={
                'db_table': 'preceptor',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='legajo_preceptor',
            field=models.ForeignKey(blank=True, db_column='legajo_preceptor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.preceptor'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('id_instalacion', models.ForeignKey(db_column='id_instalacion', on_delete=django.db.models.deletion.DO_NOTHING, to='core.instalacion')),
                ('id_persona_solicitante', models.ForeignKey(db_column='id_persona_solicitante', on_delete=django.db.models.deletion.DO_NOTHING, to='core.persona')),
                ('legajo_personal_evaluador', models.ForeignKey(db_column='legajo_personal_evaluador', on_delete=django.db.models.deletion.DO_NOTHING, to='core.personaladministrativo')),
            ],
            options={
                'db_table': 'reserva',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SolicitudViaje',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('legajo_docente', models.ForeignKey(db_column='legajo_docente', on_delete=django.db.models.deletion.DO_NOTHING, to='core.docente')),
            ],
            options={
                'db_table': 'solicitud_viaje',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Tarea', 'Tarea'), ('Evaluación', 'Evaluación')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('programa_publicacion', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado'), ('Programado', 'Programado')], default='Borrador', max_length=20)),
                ('curso_destinado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_docente', to='core.curso')),
                ('docente', models.ForeignKey(db_column='legajo_docente', on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.materia')),
            ],
            options={
                'db_table': 'tarea',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('email_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='core.persona')),
            ],
            options={
                'db_table': 'tutor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagoPendiente',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.CharField(max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField()),
                ('legajo_alumno', models.ForeignKey(db_column='legajo_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.alumno')),
                ('id_tutor', models.ForeignKey(db_column='id_tutor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tutor')),
            ],
            options={
                'db_table': 'pago_pendiente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('medio_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(default='Pagada', max_length=30)),
                ('id_legajo_alumno', models.ForeignKey(db_column='id_legajo_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.alumno')),
                ('id_tutor', models.ForeignKey(db_column='id_tutor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tutor')),
            ],
            options={
                'db_table': 'cuota',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TutorTutoraAlumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_parentesco', models.CharField(blank=True, max_length=30, null=True)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.alumno')),
                ('id_tutor', models.ForeignKey(db_column='id_tutor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tutor')),
            ],
            options={
                'db_table': 'tutor_tutora_alumno',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('motivo', models.TextField()),
                ('id_solicitud', models.OneToOneField(db_column='id_solicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='core.solicitudviaje')),
            ],
            options={
                'db_table': 'viaje',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursoParticipaViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.curso')),
                ('id_viaje', models.ForeignKey(db_column='id_viaje', on_delete=django.db.models.deletion.DO_NOTHING, to='core.viaje')),
            ],
            options={
                'db_table': 'curso_participa_viaje',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ViajeUtilizaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_uso', models.DateField()),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.vehiculo')),
                ('id_viaje', models.ForeignKey(db_column='id_viaje', on_delete=django.db.models.deletion.DO_NOTHING, to='core.viaje')),
            ],
            options={
                'db_table': 'viaje_utiliza_vehiculo',
                'managed': True,
            },
        ),
    ]
