from django.contrib import admin

from .models import (
    Alumno,
    Arancel,
    Asistencia,
    Aula,
    Calificacion,
    Cuota,
    Curso,
    CursoCursaMaterias,
    CursoParticipaViaje,
    Directivo,
    DisciplinaDeportiva,
    Docente,
    DocenteDictaMateria,
    DocenteDisciplina,
    DocumentacionAlumno,
    Evaluacion,
    Inscripcion,
    Instalacion,
    Materia,
    Noticia,
    PagoPendiente,
    Persona,
    PersonalAdministrativo,
    PostulacionLaboral,
    Preceptor,
    Reserva,
    SolicitudInscripcion,
    SolicitudViaje,
    Tarea,
    Tutor,
    TutorTutoraAlumno,
    Usuario,
    Vehiculo,
    Viaje,
    ViajeUtilizaVehiculo,
)


MODELOS_ADMINISTRABLES = (
    Alumno,
    Arancel,
    Asistencia,
    Aula,
    Calificacion,
    Cuota,
    Curso,
    CursoCursaMaterias,
    CursoParticipaViaje,
    Directivo,
    DisciplinaDeportiva,
    Docente,
    DocenteDictaMateria,
    DocenteDisciplina,
    DocumentacionAlumno,
    Evaluacion,
    Inscripcion,
    Instalacion,
    Materia,
    Noticia,
    PagoPendiente,
    Persona,
    PersonalAdministrativo,
    PostulacionLaboral,
    Preceptor,
    Reserva,
    SolicitudInscripcion,
    SolicitudViaje,
    Tarea,
    Tutor,
    TutorTutoraAlumno,
    Usuario,
    Vehiculo,
    Viaje,
    ViajeUtilizaVehiculo,
)

for modelo in MODELOS_ADMINISTRABLES:
    admin.site.register(modelo)
